"""historial

Revision ID: 5be1a338f3fd
Revises: c9489391cf4f
Create Date: 2024-09-11 11:01:06.699285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be1a338f3fd'
down_revision: Union[str, None] = 'c9489391cf4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial',
    sa.Column('idHistorial', sa.Integer(), nullable=False),
    sa.Column('Usuario_idUsuario', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horaInicio', sa.DateTime(), nullable=False),
    sa.Column('horaFin', sa.DateTime(), nullable=True),
    sa.Column('Equipo_idEquipo', sa.Integer(), nullable=False),
    sa.Column('nombreSala', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['Equipo_idEquipo'], ['equipo.idEquipo'], ),
    sa.ForeignKeyConstraint(['Usuario_idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idHistorial')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial')
    # ### end Alembic commands ###
